spring:
  profiles:
    active:
    -dev

spring:
  profiles: dev
  application: 
    name: mircoservicecloud-config-leo-dev

spring:
  profiles: test
  application:
    name: mircoservicecloud-config-leo-test