spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.10:3306/cloudDB01
    #    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC
    username: root
    password: 123456
    #    password: root
    dbcp2:
      min-idle: 5             # 最小维持连接数
      initial-size: 5         # 初始化连接数
      max-total: 5            # 最大连接数
      max-wait-millis: 200    # 等待连接获取的最大超时时间 provider-dept-8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.leo.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      #     defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: cloud-dept-8001
    prefer-ip-address: true
info:
  app.name: leo-springcloud
  comany.name: www.zhaoliwen.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  ---
  server:
    port: 8001
  spring:
    profiles: test
    application:
      name: microservicecloud-dept
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.137.10:3306/cloudDB02
      #    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC
      username: root
      password: 123456
      #    password: root
      dbcp2:
        min-idle: 5             # 最小维持连接数
        initial-size: 5         # 初始化连接数
        max-total: 5            # 最大连接数
        max-wait-millis: 200    # 等待连接获取的最大超时时间 provider-dept-8001
  mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.leo.entities
    mapper-locations:
      - classpath:mybatis/mapper/**/*.xml
  eureka:
    client:
      service-url:
        #     defaultZone: http://localhost:7001/eureka
        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    instance:
      instance-id: cloud-dept-8001
      prefer-ip-address: true
  info:
    app.name: leo-springcloud
    comany.name: www.zhaoliwen.cn
    build.artifactId: $project.artifactId$
    build.version: $project.version$
